Zip the MusicBrainz Solr configsets in the image
To speed up the container startup, zip the Musicbrainz Solr configsets
directly in the image so that it doesn’t need to be zipped at run time.

The script is still able to zip configsets if needed for development.

diff --git a/docker/scripts/create-musicbrainz-collections b/docker/scripts/create-musicbrainz-collections
--- a/docker/scripts/create-musicbrainz-collections
+++ b/docker/scripts/create-musicbrainz-collections
@@ -8,7 +8,7 @@ UPLOAD_URL="http://localhost:8983/api/cluster/configs"
 EXCLUDE_DIRS="lib common _template"
 
 # Populate the list of subdirectories
-SUBDIRS=$(find $MAIN_DIR -maxdepth 1 -mindepth 1 -type d -print0 | xargs -0 -n 1 basename)
+SUBDIRS=$(find $MAIN_DIR -maxdepth 1 -mindepth 1 -type d -print0 | xargs -0 -n 1 basename | sort)
 
 # Exclude specified directories
 if [ -n "$EXCLUDE_DIRS" ]; then
@@ -17,38 +17,46 @@ if [ -n "$EXCLUDE_DIRS" ]; then
     done
 fi
 
+# Go to the main directory for mbsssss
+cd "$MAIN_DIR" >/dev/null
+
 # Iterate over the filtered subdirectories
 for SUBDIR in $SUBDIRS; do
     FULL_PATH="$MAIN_DIR/$SUBDIR/conf"
     FULL_PATH=$(realpath "$FULL_PATH")
+    ZIP_FILE="$MAIN_DIR/$SUBDIR.zip"
 
-    # Check if the subdirectory exists
-    if [ ! -d "$FULL_PATH" ]; then
-        echo >&2 "Directory $FULL_PATH does not exist."
-        exit 66 # EX_NOINPUT
-    fi
+    # Check if the zip file exists
+    if [ ! -f "$ZIP_FILE" ]; then
+        # Check if the subdirectory exists
+        if [ ! -d "$FULL_PATH" ]; then
+            echo >&2 "Directory $FULL_PATH does not exist."
+            exit 66 # EX_NOINPUT
+        fi
 
-    # Change to the directory being zipped
-    cd "$FULL_PATH" || {
-        echo >&2 "Failed to change to directory $FULL_PATH."
-        exit 74 # EX_IOERR
-    }
+        # Change to the directory being zipped
+        cd "$FULL_PATH" || {
+            echo >&2 "Failed to change to directory $FULL_PATH."
+            exit 74 # EX_IOERR
+        }
 
-    # Create a zip file of the subdirectory
-    ZIP_FILE="$SUBDIR.zip"
-    echo "Zipping $FULL_PATH into $ZIP_FILE..."
-    if ! zip -r "$ZIP_FILE" -- * >/dev/null; then
-        echo >&2 "Error zipping $FULL_PATH."
+        # Create a zip file of the subdirectory
+        ZIP_FILE="$MAIN_DIR/$SUBDIR.zip"
+        echo "Zipping $FULL_PATH into $ZIP_FILE..."
+        if ! zip -r "$ZIP_FILE" -- * >/dev/null; then
+            echo >&2 "Error zipping $FULL_PATH."
+            exit 73 # EX_CANTCREAT
+        fi
+
+        # Return to the original directory
         cd - >/dev/null
-        exit 73 # EX_CANTCREAT
     fi
 
     # Make the curl PUT request
     echo "Uploading $ZIP_FILE to $UPLOAD_URL..."
     if curl -X PUT --header "Content-Type:application/octet-stream" --data-binary @"$ZIP_FILE" "$UPLOAD_URL/$SUBDIR"; then
         echo ""
-        echo "Upload successful. Deleting $ZIP_FILE..."
-        rm "$ZIP_FILE"
+        echo "Upload successful."
 
         echo "Creating collection $SUBDIR..."
         curl -X POST http://localhost:8983/api/collections \
@@ -58,13 +66,9 @@ for SUBDIR in $SUBDIRS; do
                 \"config\": \"${SUBDIR}\",
                 \"numShards\": 1
             }"
-        echo ""
     else
         echo ""
         echo "Upload failed for $ZIP_FILE. Keeping the file for debugging."
     fi
-
-    # Return to the original directory
-    cd - >/dev/null
 
 done
